# Primera Parte: Gerencia (Ágil) de Proyectos

La gerencia o dirección de proyectos se suele ejercer como una profesión que sigue los estándares o recomendaciones de buenas prácticas reconocidas por el [Project Management Institute](https://www.pmi.org/). Aunque la primera versión de estos estándares fue publicada por el Instituto Nacional de Estándares de los Estados Unidos en 1987, otras versiones han sido conocidas posteriormente hasta el 2017 cuando se publicó la sexta versión. Estos estándares incluyen un conjunto de conocimientos y prácticas que se pueden aplicar en la mayoría de los proyectos y que con un margen razonablemente alto de confianza pueden aumentar las posibilidades de culminar con éxito tales proyectos.

El término **Gerencia Ágil de Proyectos**, por su parte, suele estar muy vinculado a la gestión de proyectos especialmente dirigidos al desarrollo de software [@Dyba2014], desde que la **metodología SCRUM** fue acuñada por @Schwaber1997. La metodología SCRUM puede ser usada o aplicada a proyectos que no necesariamente suponen el desarrollo de un software o producto tecnológico, aunque sí requieran de software para mantener el control y gestionar las diferentes fases de un proyecto orientado al desarrollo de servicios, al desarrollo social y económico, o simplemente al estudio de [**sistemas complejos**](https://complexityexplained.github.io/ComplexityExplained%5BSpanish%5D.pdf). Para los profesionales que no han escuchado acerca de los sistemas complejos, puede resultar valioso advertir de entrada que lo complejo de un sistema no debe ser confundido con lo complicado que pueda resultar estudiarlo.

## Complejidad y Gerencia de Proyectos.

Los sistemas complejos son un objeto de estudio científico. Aunque existen múltiples institutos, laboratorios y universidades que brindan formación en sistemas complejos, sus esfuerzos suelen coincidir y divulgarse a través de una red profesional conocida como la [Sociedad de Sistemas Complejos](https://cssociety.org/home).

Según Hiroki Sayama [-@Sayama2015], los sistemas complejos son redes constituidas por una serie de componentes que interactúan entre sí, normalmente de forma no lineal que pueden surgir y evolucionar a través de la auto-organización (sin la intervención de un gerente o líder), y sin llegar a ser ni completamente predecibles ni completamente aleatorios, pueden mostrar comportamientos emergentes que solo resultan visibles cuando vemos al sistema cambiando la perspectiva de una escala local o microscópica a otra escala general o macroscópica.

Los cuatro casos que presentamos en este libro comparten la inspiración de aplicar la perspectiva de los sistemas complejos. Estos sistemas suelen caracterizarse por tener muchos componentes que interactúan de formas múltiples entre sí y potencialmente con su entorno. Estas partes forman redes de interacciones, a veces con unos pocos componentes involucrados en muchas interacciones. Las interacciones pueden generar información nueva que complica el estudio individual de las partes o la predicción correcta de su futuro. Adicionalmente, los componentes de un sistema pueden también ser nuevos sistemas, es decir, sistemas de sistemas interdependientes entre sí. El mayor reto de las ciencias de la complejidad no es sólo apreciar las partes y sus conexiones, sino también entender cómo estas interacciones dan lugar al todo.
