# Activación economía Montería-Córdoba

## Situación Problema
Este proyecto busca financiar iniciativas empresariales de diferentes sectores que sean desarrolladas por emprendedores que residan en la ciudad de Montería, departamento de Córdoba.

```{r}
#setwd("~/GitHub/APGPAC/Data") 
library(readr)
EMPRESAS_REGISTRADAS_MONTERIA_2005_2019_20241011 <- read_delim("Data/EMPRESAS_REGISTRADAS_MONTERIA_2005-2019_20241011_V2.csv",
                                                               delim = ";", escape_double = FALSE, trim_ws = TRUE)

Empresas=EMPRESAS_REGISTRADAS_MONTERIA_2005_2019_20241011


library(dplyr)#este paquete sirve para filtar

Monteria=Empresas %>%
          filter(`MUN-NOTIFICACION`=="23001 - MONTERIA")

library(agricolae)#para hacer tablas de frecuencias v cuantitativas
library(fdth)  #para hacer tablas de frecuencias cualitativas
tabla1=fdt_cat(Monteria$`CIIU-1`);tabla1

#tabla de frecuencias
table(Monteria$`CIIU-1`)

MonteriaActividades <- data.frame(table(Monteria$Actividad))
MonteriaActividadesDesc <- MonteriaActividades %>%
  arrange(desc(Freq))
MonteriaActividadesPrincipales <- head(MonteriaActividadesDesc, 10)


#diagrama barras

#setwd("~/GitHub/APGPAC/Data")
library(readr)
EMPRESAS_REGISTRADAS_MONTERIA_2005_2019_20241011 <- read_delim("Data/EMPRESAS_REGISTRADAS_MONTERIA_2005-2019_20241011_V2.csv",
                                                               delim = ";", escape_double = FALSE, trim_ws = TRUE)

Empresas=EMPRESAS_REGISTRADAS_MONTERIA_2005_2019_20241011


library(dplyr)#este paquete sirve para filtar

Monteria=Empresas %>%
          filter(`MUN-NOTIFICACION`=="23001 - MONTERIA")

library(agricolae)#para hacer tablas de frecuencias v cuantitativas
library(fdth)  #para hacer tablas de frecuencias cualitativas
tabla1=fdt_cat(Monteria$`CIIU-1`);tabla1

#tabla de frecuencias
table(Monteria$`CIIU-1`)

MonteriaActividades <- data.frame(table(Monteria$Actividad))
MonteriaActividadesDesc <- MonteriaActividades %>%
  arrange(desc(Freq))
MonteriaActividadesPrincipales <- head(MonteriaActividadesDesc, 10)


#diagrama barras

library(ggplot2)
# Assuming your data frame is named "MonteriasActividades" with variables "Var1" and "Freq"
ggplot(MonteriaActividadesPrincipales,
       aes(x = reorder(Var1, Freq, FUN = "mean"), y = Freq)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  coord_flip() +
  labs(title = "Diagrama de barras para Actividad Monteria",#titulo
       x = "Actividad",#titulo eje x
       y = "Frequencia" #titulo eje y
       ) +
  theme_minimal()
```


## Agencia Financiadora del Proyecto
La agencia financiadora de este proyecto es el FONDO EMPRENDER. Su objetivo general es incentivar y facilitar la generación y creación de empresas, contribuyendo al desarrollo humano y la inserción de estas en el sector productivo. De esta manera, se busca coadyuvar al desarrollo social y económico del país a través de una formación pertinente y la provisión de capital semilla.

## Datos relevantes del Proyecto

### Monto financiado
Para la presente convocatoria, el Fondo Emprender entregará recursos de hasta SETENTA MILLONES DE PESOS M/CTE ($70.000.000,00). Lo anterior, si el plan de negocio genera hasta tres (3) o más empleos formales y directos.

### Sectores económicos de la convocatoria
Multisectorial.

### Fechas importantes
Apertura: 18 de septiembre de 2024
Cierre: 18 de noviembre de 2024

### Requisitos para aplicar
1. Ser colombiano. 
2. Ser mayor de edad y contar con plenas facultades legales para suscribir contratos. 
3. No encontrarse sujeto a un conflicto de intereses, inhabilidades e incompatibilidades, de acuerdo con lo indicado en la Constitución Nacional. 
4. No tener nexos de parentesco hasta el cuarto grado de consanguinidad, segundo de afinidad, y primero civil con funcionarios o contratistas del SENA en el nivel directivo del orden nacional o del orden regional en donde se presenta el plan de negocio. Esta restricción aplica a los funcionarios o contratistas de los Centros de Desarrollo Empresarial y Unidades Externas de Emprendimiento vinculadas al programa de Fondo Emprender, así como evaluadores, operadores y demás personas que tengan injerencia en el proceso. 
5. No habérsele asignado anteriormente recursos del Fondo Emprender por parte del Consejo Directivo Nacional del SENA – CDN. 
6. No estar incurso en ninguna causal de inhabilidad o incompatibilidad consagradas en la ley para contratar con el Estado. 
7. No estar desempeñando ningún cargo público. 
8. No contar con ningún tipo de vinculación laboral o contractual con el Servicio Nacional de Aprendizaje - SENA, exceptuando el contrato de aprendizaje. 
9. La dedicación de los beneficiarios al proyecto deberá ser de tiempo completo y exclusivo, salvo que, se justifique la dedicación parcial, indicando su compromiso de asistir directa y personalmente a todas las citaciones que realicen el SENA, el operador de los recursos o la interventoría. 


